# -*- coding: utf-8 -*-
"""CL Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OtYAdnEjvD5Kag0aE9n6Gr0l0Ez2KA-
"""

!pip install transformers torch googletrans==4.0.0-rc1

from transformers import MarianMTModel, MarianTokenizer
from googletrans import Translator

# Method 1: Using Hugging Face MarianMT
def translate_text_huggingface(text, src_lang="en", tgt_lang="es"):
    model_name = f'Helsinki-NLP/opus-mt-{src_lang}-{tgt_lang}'

    # Load the tokenizer and modelmodel
    tokenizer = MarianTokenizer.from_pretrained(model_name)
    model = MarianMTModel.from_pretrained(model_name)

    # Tokenize input text
    tokenized_text = tokenizer.encode(text, return_tensors="pt")

    # Translate the text
    translated = model.generate(tokenized_text, num_beams=4, max_length=50, early_stopping=True)

    # Decode the translated text
    translated_text = tokenizer.decode(translated[0], skip_special_tokens=True)

    return translated_text

# Method 2: Using Google Translate API
def translate_text_google(text, src_lang='en', tgt_lang='es'):
    translator = Translator()

    # Perform translation
    translated = translator.translate(text, src=src_lang, dest=tgt_lang)

    return translated.text

# Main function to get user input and display translation results
def main():
    # User input for sentence
    text = input("Enter a sentence to translate: ")

    # User input for source and target languages
    src_lang = input("Enter the source language code (e.g., 'en' for English, 'es' for Spanish): ")
    tgt_lang = input("Enter the target language code (e.g., 'es' for Spanish, 'fr' for French): ")

    # Translation using Hugging Face model
    translated_huggingface = translate_text_huggingface(text, src_lang, tgt_lang)
    print("\n--- Translation using Hugging Face MarianMT ---")
    print("Original Text:", text)
    print("Translated Text (Hugging Face):", translated_huggingface)

    # Translation using Google Translate API
    translated_google = translate_text_google(text, src_lang, tgt_lang)
    print("\n--- Translation using Google Translate API ---")
    print("Original Text:", text)
    print("Translated Text (Google Translate):", translated_google)

# Run the program
if __name__ == "__main__":
    main()